In [106]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
matplotlib.style.use('ggplot')
# use the code below to make sure plot is shown in Notebook
%matplotlib inline

In [321]:
Train_cleaned = pd.read_csv('F:\MSBAPM\Travellers\Train_final2.csv')

In [322]:
Train_cleaned.cancel.value_counts()

0    5706
1    1843
Name: cancel, dtype: int64

In [323]:
Train_cleaned.columns

Index(['id', 'tenure', 'claim.ind', 'n.adults', 'n.children', 'ni.gender',
       'ni.marital.status', 'premium', 'sales.channel', 'coverage.type',
       'dwelling.type', 'len.at.res_withoutotliers', 'credit', 'house.color',
       'ni.age_withoutoutliers', 'year', 'combo1', 'zip.code', 'cancel',
       'Premium range', 'Combo2_final', 'zip.code.1'],
      dtype='object')

In [369]:
#define x and y parameters
feature_cols = [ 'tenure', 'claim.ind', 'n.adults', 'n.children', 'ni.marital.status', 'Premium range',  'sales.channel', 
        'len.at.res_withoutotliers', 'credit', 'ni.age_withoutoutliers', 'zip.code.1']

In [370]:
# X is a matrix, hence we use [] to access the features we want in feature_cols
X1 = Train_cleaned[feature_cols]

In [371]:
X1.head()

,tenure,claim.ind,n.adults,n.children,ni.marital.status,Premium range,sales.channel,len.at.res_withoutotliers,credit,ni.age_withoutoutliers,zip.code.1
0,12,0,4,2,1,800,1,13.0,1,47.0,800
1,18,0,2,0,1,800,1,15.0,1,47.0,500
2,4,0,2,0,0,1000,2,10.0,2,30.0,500
3,16,0,1,0,1,1000,1,22.0,1,38.0,800
4,14,0,3,3,1,800,2,18.0,3,49.0,500

NameError: name 'Combo2_final' is not defined

In [372]:
# y is a vector, hence we use dot to access 'label'
y1 = Train_cleaned.cancel

# Logistic Model

In [328]:
# split X and y into training and testing sets
from sklearn.cross_validation import train_test_split
X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, random_state=0)

In [329]:
# train a logistic regression model on the training set
from sklearn.linear_model import LogisticRegression

# instantiate model
logreg = LogisticRegression()

# fit model
model = logreg.fit(X1_train, y1_train)

In [330]:
# make class predictions for the testing set
y1_pred_class = model.predict(X1_test)

In [252]:
# print the first 25 true and predicted responses
#print('True:', y_test.values[0:100])
#print('False:', y_pred_class[0:1000])
#print('False:', y_train.values[0:100])
y1_pred_class

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [295]:
np.unique(y1_pred_class)

array([0, 1], dtype=int64)

In [331]:
# calculate accuracy
from sklearn import metrics
print(metrics.accuracy_score(y1_test, y1_pred_class))

0.775423728814

In [332]:
from sklearn.metrics import roc_auc_score

In [333]:
#sorting

r = model.predict_proba(X1_test)
r
r1 = sorted(r[:,1], reverse = True)

In [334]:
r

array([[ 0.88057712,  0.11942288],
       [ 0.92937307,  0.07062693],
       [ 0.88148609,  0.11851391],
       ...,
       [ 0.82556042,  0.17443958],
       [ 0.90465144,  0.09534856],
       [ 0.90101764,  0.09898236]])

In [335]:
#roc_auc_score(y1_test,r[:,1])
roc_auc_score(y1_test,r1)

0.49692145920796332

In [337]:
r = model.predict_proba(X1_test)
r
roc_auc_score(y1_test,r[:,1])

0.6862207679662512

# Random Forest Classifier

In [338]:
from sklearn.ensemble import RandomForestClassifier
obj = RandomForestClassifier()
obj.fit(X1_train, y1_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=10, n_jobs=1, oob_score=False, random_state=None,
            verbose=0, warm_start=False)

In [339]:
#roc_auc_score(y,obj[:,1])
result1 = obj.predict_proba(X1_test)
result1

array([[ 1. ,  0. ],
       [ 1. ,  0. ],
       [ 0.9,  0.1],
       ...,
       [ 0.8,  0.2],
       [ 0.9,  0.1],
       [ 0.9,  0.1]])

In [340]:
r1 = sorted(result1[:,1], reverse = True)
roc_auc_score(y1_test,r1)

0.49795416899770739

In [341]:
roc_auc_score(y1_test,result1[:,1])

0.64520228731898199

# Test Data

In [354]:
Train_test = pd.read_csv('F:\MSBAPM\Travellers\Test_final.csv')

In [356]:
Train_test.columns

Index(['id', 'tenure', 'claim.ind', 'n.adults', 'n.children', 'ni.gender',
       'ni.marital.status', 'premium', 'sales.channel', 'coverage.type',
       'dwelling.type', 'len.at.res', 'credit', 'house.color', 'ni.age',
       'year', 'zip.code', 'cancel', 'Premium Range', 'combo2', 'combo1'],
      dtype='object')

In [373]:
Train_test.head()

,id,tenure,claim.ind,n.adults,n.children,ni.gender,ni.marital.status,premium,sales.channel,coverage.type,...,len.at.res,credit,house.color,ni.age,year,zip.code,cancel,Premium Range,combo2,combo1
0,7583,5,0,1,3,1,1,913.62,1,C,...,18.0,2,blue,35,2017,850,1,800,101800,36
1,7584,15,1,1,4,1,1,1018.43,2,A,...,15.0,2,white,59,2017,980,1,1000,1111000,5
2,7585,1,1,3,2,0,1,928.42,1,B,...,13.0,2,blue,27,2017,150,1,800,11800,27
3,7586,12,0,4,0,0,0,877.65,1,B,...,19.0,1,blue,35,2017,150,1,800,800,27
4,7587,11,0,1,9,1,1,947.28,1,A,...,18.0,1,red,34,2017,150,1,800,101800,3

In [374]:
#define x and y parameters
feature_cols = [ 'tenure', 'claim.ind', 'n.adults', 'n.children', 'ni.marital.status', 'premium',  'sales.channel', 
        'len.at.res', 'credit', 'ni.age', 'zip.code']

In [375]:
X2 = Train_test[feature_cols]

In [376]:
X2.head()

,tenure,claim.ind,n.adults,n.children,ni.marital.status,premium,sales.channel,len.at.res,credit,ni.age,zip.code
0,5,0,1,3,1,913.62,1,18.0,2,35,850
1,15,1,1,4,1,1018.43,2,15.0,2,59,980
2,1,1,3,2,1,928.42,1,13.0,2,27,150
3,12,0,4,0,0,877.65,1,19.0,1,35,150
4,11,0,1,9,1,947.28,1,18.0,1,34,150

In [397]:
# make class predictions for the testing set
y2 = gradient.predict(X2)
y2

array([0, 0, 0, ..., 0, 0, 1], dtype=int64)

In [222]:
y2[0:50]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0], dtype=int64)

In [1]:
r1 = gradient.predict_proba(X2)
r1[:,1]

NameError: name 'gradient' is not defined

In [399]:
Train_test['output'] = r1[:,1]

In [400]:
Train_test.head()

,id,tenure,claim.ind,n.adults,n.children,ni.gender,ni.marital.status,premium,sales.channel,coverage.type,...,credit,house.color,ni.age,year,zip.code,cancel,Premium Range,combo2,combo1,output
0,7583,5,0,1,3,1,1,913.62,1,C,...,2,blue,35,2017,850,1,800,101800,36,0.190027
1,7584,15,1,1,4,1,1,1018.43,2,A,...,2,white,59,2017,980,1,1000,1111000,5,0.464289
2,7585,1,1,3,2,0,1,928.42,1,B,...,2,blue,27,2017,150,1,800,11800,27,0.127449
3,7586,12,0,4,0,0,0,877.65,1,B,...,1,blue,35,2017,150,1,800,800,27,0.092921
4,7587,11,0,1,9,1,1,947.28,1,A,...,1,red,34,2017,150,1,800,101800,3,0.167470

In [401]:
Train_test.to_csv('F:\MSBAPM\Travellers\Test_Final_ver3.0.csv')

In [1]:
roc_auc_score(y1_test,r1[:,1])

NameError: name 'roc_auc_score' is not defined

In [225]:
Train_Final = Train_test

In [227]:
Train_Final.head()

,id,tenure,claim.ind,n.adults,n.children,ni.gender,Gender_numeric,ni.marital.status,premium,sales.channel,Sales_numerical,coverage.type,dwelling.type,len.at.res,credit,Credit_numerical,house.color,ni.age,year,zip.code
0,7583,5,0,1,3,F,0,1,913.623201,Broker,2,C,Tenant,18.0,medium,1,blue,35.0,2017,85066
1,7584,15,1,1,4,F,0,1,1018.426114,Phone,1,A,House,15.0,medium,1,white,59.0,2017,98013
2,7585,1,1,3,2,M,1,1,928.418533,Broker,2,B,Condo,13.0,medium,1,blue,27.0,2017,15049
3,7586,12,0,4,0,M,1,0,877.649917,Broker,2,B,Condo,19.0,high,2,blue,35.0,2017,15026
4,7587,11,0,1,9,F,0,1,947.281913,Broker,2,A,Condo,18.0,high,2,red,34.0,2017,15025

In [235]:
output = pd.Series(y2)

In [239]:
Train_Final['output'] = y2

In [240]:
Train_Final.head()

,id,tenure,claim.ind,n.adults,n.children,ni.gender,Gender_numeric,ni.marital.status,premium,sales.channel,...,dwelling.type,len.at.res,credit,Credit_numerical,house.color,ni.age,year,zip.code,Output,output
0,7583,5,0,1,3,F,0,1,913.623201,Broker,...,Tenant,18.0,medium,1,blue,35.0,2017,85066,0,0
1,7584,15,1,1,4,F,0,1,1018.426114,Phone,...,House,15.0,medium,1,white,59.0,2017,98013,0,0
2,7585,1,1,3,2,M,1,1,928.418533,Broker,...,Condo,13.0,medium,1,blue,27.0,2017,15049,0,0
3,7586,12,0,4,0,M,1,0,877.649917,Broker,...,Condo,19.0,high,2,blue,35.0,2017,15026,0,0
4,7587,11,0,1,9,F,0,1,947.281913,Broker,...,Condo,18.0,high,2,red,34.0,2017,15025,0,0

In [242]:
type(output)

pandas.core.series.Series

In [250]:
Train_Final.output.value_counts()

0    2250
1     131
Name: output, dtype: int64

In [253]:
Train_Final = Train_Final.drop(['Output'],axis = 1)

In [254]:
Train_Final.head()

,id,tenure,claim.ind,n.adults,n.children,ni.gender,Gender_numeric,ni.marital.status,premium,sales.channel,...,coverage.type,dwelling.type,len.at.res,credit,Credit_numerical,house.color,ni.age,year,zip.code,output
0,7583,5,0,1,3,F,0,1,913.623201,Broker,...,C,Tenant,18.0,medium,1,blue,35.0,2017,85066,0
1,7584,15,1,1,4,F,0,1,1018.426114,Phone,...,A,House,15.0,medium,1,white,59.0,2017,98013,0
2,7585,1,1,3,2,M,1,1,928.418533,Broker,...,B,Condo,13.0,medium,1,blue,27.0,2017,15049,0
3,7586,12,0,4,0,M,1,0,877.649917,Broker,...,B,Condo,19.0,high,2,blue,35.0,2017,15026,0
4,7587,11,0,1,9,F,0,1,947.281913,Broker,...,A,Condo,18.0,high,2,red,34.0,2017,15025,0

In [255]:
Train_Final.to_csv('F:\MSBAPM\Travellers\Train_Final.csv')

# Decision Tree Model

In [95]:
#Import Library
from sklearn import tree
from sklearn.metrics import roc_auc_score

In [97]:
# split X and y into training and testing sets
from sklearn.cross_validation import train_test_split
X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, test_size = 0.3,random_state=0)

In [81]:
# Create tree object 
decision = tree.DecisionTreeClassifier() 
# for classification, here you can change the algorithm as gini or entropy (information gain) by default it is gini  
# model = tree.DecisionTreeRegressor() for regression
decision

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [82]:
# Train the model using the training sets and check score
decision.fit(X1_train, y1_train)
decision.score(X1_train, y1_train)

1.0

In [83]:
#Predict Output
y_predict= decision.predict(X1_test)

In [84]:
from sklearn.metrics import accuracy_score
accuracy_score(y1_test, y_predict)

0.66701846965699207

In [86]:
#roc_auc_score(y,obj[:,1])
result = decision.predict_proba(X1_test)
result

array([[ 1.,  0.],
       [ 1.,  0.],
       [ 0.,  1.],
       ...,
       [ 0.,  1.],
       [ 1.,  0.],
       [ 0.,  1.]])

In [87]:
roc_auc_score(y1_test,result[:,1])

0.55037786995101912

In [88]:
#Confusion Matrix
from sklearn.metrics import confusion_matrix

pd.DataFrame(
    confusion_matrix(y1_test, y_predict),
    columns=['Predicted 0', 'Predicted 1'],
    index=['True 0', 'True 1']
)

        Predicted 0  Predicted 1
True 0         1115          319
True 1          312          149

# GBM

In [389]:
#Import Library
from sklearn import tree
from sklearn.metrics import roc_auc_score
from sklearn.ensemble import GradientBoostingClassifier

In [390]:
# split X and y into training and testing sets
from sklearn.cross_validation import train_test_split
X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, random_state=0)

In [391]:
gradient = GradientBoostingClassifier()
gradient

GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.1, loss='deviance', max_depth=3,
              max_features=None, max_leaf_nodes=None,
              min_impurity_split=1e-07, min_samples_leaf=1,
              min_samples_split=2, min_weight_fraction_leaf=0.0,
              n_estimators=100, presort='auto', random_state=None,
              subsample=1.0, verbose=0, warm_start=False)

In [392]:
gradient.fit(X1_train, y1_train)
gradient.score(X1_train, y1_train)

0.78625684508037452

In [395]:
#roc_auc_score(y,obj[:,1])
result = gradient.predict_proba(X1_test)
result

array([[ 0.9315239 ,  0.0684761 ],
       [ 0.96029518,  0.03970482],
       [ 0.81269331,  0.18730669],
       ...,
       [ 0.79143407,  0.20856593],
       [ 0.88289949,  0.11710051],
       [ 0.88816545,  0.11183455]])

In [349]:
r1 = sorted(result[:,1], reverse = True)
r1

[0.89922201423975867,
 0.87332707899948669,
 0.82080501602391065,
 0.80625365189143272,
 0.77866647599629668,
 0.77663723891451153,
 0.77333593704345971,
 0.76444909396239025,
 0.75490617786698389,
 0.75004836261793639,
 0.74429420508429867,
 0.74356586614866205,
 0.72365115242478895,
 0.69628948345374897,
 0.68776923595126682,
 0.68454595945745245,
 0.66593980192413516,
 0.66415325637373235,
 0.66308372093075463,
 0.66109026650868441,
 0.65968803694898825,
 0.65135386654868643,
 0.64240398958248246,
 0.64160050881372166,
 0.63830082873615124,
 0.6356668977433978,
 0.63469275405029801,
 0.63406297361561703,
 0.63292569322344749,
 0.63127588607164886,
 0.63093558325029764,
 0.63059342579048394,
 0.62658899688753367,
 0.62576490910889693,
 0.62308718824573828,
 0.62023320827718598,
 0.6201277627677596,
 0.6196053759306217,
 0.61762161659499948,
 0.61614701759925317,
 0.61156939642365271,
 0.61147363459922921,
 0.61072276051139951,
 0.60932749371031025,
 0.60440076333380977,
 0.60227912885301071,
 0.60214625069451855,
 0.60156139195053426,
 0.60066479118306315,
 0.60004395331286542,
 0.59888150068403978,
 0.59821819697293743,
 0.59649771493948545,
 0.59430885688882906,
 0.59378661733689309,
 0.59361434343131581,
 0.59327422888087189,
 0.5897931847910528,
 0.58669251909507225,
 0.58580675431017526,
 0.57787989197510969,
 0.57734626075494877,
 0.57585830788478742,
 0.57552866355699073,
 0.57483797269407977,
 0.57305313508734979,
 0.57172343188127195,
 0.57134698968877951,
 0.57066516018846214,
 0.56756872962710991,
 0.56742998008721657,
 0.5662484182487254,
 0.56345832015093555,
 0.56130055489701658,
 0.56123669971759471,
 0.56039855246340486,
 0.55913005213097777,
 0.55845907123806027,
 0.55555420397905275,
 0.55459850623280804,
 0.55287237309414439,
 0.55228953974084827,
 0.55189716692470969,
 0.55162788019692843,
 0.54949011970329587,
 0.54717560229937623,
 0.54363381375571973,
 0.54077354215586482,
 0.54065310550873913,
 0.54012106364520418,
 0.53990134785060462,
 0.53973855410320937,
 0.53945379679960548,
 0.5388702755742214,
 0.536973457427386,
 0.53433803681093051,
 0.5330986120563227,
 0.53195485934350339,
 0.53022531307085941,
 0.52885305921510595,
 0.52847440694622938,
 0.52782189376615718,
 0.52699593782888754,
 0.52109556434761795,
 0.52083792116712269,
 0.52050212891584768,
 0.51899559813754115,
 0.51817521009453171,
 0.51775675825607703,
 0.51769882140815793,
 0.51656983896936459,
 0.51611788237118372,
 0.51514071833193342,
 0.51498475088722406,
 0.51265947461419303,
 0.5122248077504723,
 0.51117040696155136,
 0.51083334329575181,
 0.51010342917147966,
 0.50993362570103062,
 0.50633909061894655,
 0.50508099637925652,
 0.50484464884490776,
 0.50375746332295135,
 0.50247035055541267,
 0.50244509546363869,
 0.50214272806000726,
 0.50110146932793176,
 0.50027934822305575,
 0.50016834834831914,
 0.49995159279594426,
 0.4994388175520636,
 0.4988519335223246,
 0.49825690931292227,
 0.49817465607323852,
 0.49809664144980537,
 0.49806856787586201,
 0.49796714072520804,
 0.49728441912031385,
 0.49425830789108488,
 0.49275094879993209,
 0.49269339970605613,
 0.49269339970605613,
 0.49220356331365045,
 0.49182683733939964,
 0.49118923405143966,
 0.49080113493318034,
 0.49017182252602487,
 0.48952708889148433,
 0.48874841503959854,
 0.48827014160048315,
 0.48718735609598585,
 0.48695962018853789,
 0.48516486692400318,
 0.48410367094876799,
 0.48375089212415778,
 0.48342165834966261,
 0.48155242003230098,
 0.48139482956583102,
 0.4805956171477776,
 0.48001758412296591,
 0.47902446879525556,
 0.47856067161378613,
 0.47798954522188175,
 0.47790420968010905,
 0.47768409825895086,
 0.47762130612602899,
 0.47686165979170814,
 0.47618450373470084,
 0.47279203727121816,
 0.47277096104823108,
 0.47072841059170667,
 0.47039729689840204,
 0.47024198601159806,
 0.46881744820463178,
 0.4677428530719247,
 0.46695475426075383,
 0.46629215334351903,
 0.46526309709201685,
 0.46488082283387039,
 0.46455923097818924,
 0.46421854387915107,
 0.4641877139655749,
 0.46269256129164782,
 0.45957280454985994,
 0.45896319009209557,
 0.45854391036333281,
 0.45746126380556867,
 0.45570357394745381,
 0.45514273582190562,
 0.45434207917334407,
 0.45407515071164323,
 0.45384711419740181,
 0.45344746195994456,
 0.45312306661619373,
 0.45287776793622736,
 0.45275935380692928,
 0.45205859442504837,
 0.45188027529423697,
 0.45136459088528863,
 0.44931067426497628,
 0.44913310032777121,
 0.44806324340154308,
 0.44782203082410454,
 0.44680834812302428,
 0.44677479956349225,
 0.44597764918217542,
 0.44558702427825958,
 0.44308109867168582,
 0.44049274820623968,
 0.43871365759276909,
 0.43724098190554594,
 0.43720721856984124,
 0.43638484396682725,
 0.43612101780649992,
 0.4360304286035252,
 0.43529144578351092,
 0.43462743062580927,
 0.43390939783155219,
 0.43361352800834141,
 0.43355586459017903,
 0.43343491446613724,
 0.43206881212092874,
 0.43151325088396653,
 0.43132892955650315,
 0.43007634019858759,
 0.42993118564672983,
 0.42991140273423145,
 0.42950092850701838,
 0.42929657795673742,
 0.42858990690852655,
 0.4280796843645493,
 0.42664951057402639,
 0.42593437772316445,
 0.4253276159080101,
 0.42422236174550243,
 0.4242150324443274,
 0.42318816447644081,
 0.42280307053257626,
 0.42043661282378492,
 0.42042050125973424,
 0.4203265535112401,
 0.4196128509214101,
 0.41933515807729244,
 0.41838878621952502,
 0.41834633175381147,
 0.41589381677323456,
 0.41508556516711287,
 0.4149309368811846,
 0.41454799276686216,
 0.41427849391285776,
 0.41323428416042357,
 0.41220958754400555,
 0.41207370598797055,
 0.41121635657519273,
 0.41033903958001006,
 0.40899178696143546,
 0.40895767982111331,
 0.40874389389529447,
 0.40817106535393871,
 0.4081257600610963,
 0.40778805220156628,
 0.4062663509704138,
 0.40617201618417204,
 0.40551876632045913,
 0.40504698434513475,
 0.40492860107343381,
 0.4047061062466627,
 0.40368924700674341,
 0.40277018165821227,
 0.4026407091909549,
 0.40208301319516215,
 0.40204082808807978,
 0.40171002423203872,
 0.40086854060781324,
 0.40051036894200925,
 0.40034037017528507,
 0.40022993730676554,
 0.39780288474337272,
 0.39736312100472065,
 0.3973232376278209,
 0.39682436497806972,
 0.39643487731466692,
 0.39635252685229216,
 0.39481932988661816,
 0.39442060300203113,
 0.39385826193208234,
 0.39374569591226793,
 0.39314249656163008,
 0.39196667154997777,
 0.39195755187716946,
 0.39154086313930975,
 0.39151649467940786,
 0.39145049280070765,
 0.39107903319125464,
 0.3909070143628095,
 0.39090601343892023,
 0.39048259209755631,
 0.39027066839559671,
 0.39008240525240029,
 0.38999857950384625,
 0.38973271636790424,
 0.38910748827321989,
 0.38845339538811352,
 0.38787379420821966,
 0.38643747275548634,
 0.38545661839783651,
 0.38351107342994073,
 0.38328812675413831,
 0.38229825788545735,
 0.38226041935728028,
 0.38176199805369188,
 0.38169507261841773,
 0.38111374138064308,
 0.38080760569519501,
 0.38036367565500251,
 0.37930842444071383,
 0.37917824816465029,
 0.37823812581848287,
 0.37704321392176304,
 0.3767002008318095,
 0.37661155031333687,
 0.37650449076455128,
 0.37646702139215171,
 0.37635204418908086,
 0.37582492020520253,
 0.37509730875738895,
 0.37347115686062782,
 0.37332368413416495,
 0.3728649979527715,
 0.37283067575796075,
 0.37221828204108914,
 0.37216030742390183,
 0.37214180725603696,
 0.37213515920735257,
 0.3720523573057643,
 0.3720101077769285,
 0.37195498356654993,
 0.37195498356654993,
 0.37174235483653889,
 0.37149593108707302,
 0.36992827395910499,
 0.36939236299700762,
 0.36887825986389988,
 0.36827845545587073,
 0.3678354998738792,
 0.36747613325283718,
 0.36703662830440559,
 0.36628754147881853,
 0.3658569316548308,
 0.36549595495813747,
 0.36438481308938486,
 0.3638886213001552,
 0.36365056134724927,
 0.36322267585168277,
 0.36321503565181712,
 0.36285904780273887,
 0.36195994402349979,
 0.36156589350252311,
 0.36099989513498831,
 0.36088910303689575,
 0.3605525152570272,
 0.36047785230014862,
 0.3603701662480297,
 0.35988840395601562,
 0.35973049482410363,
 0.3589704389591421,
 0.3589422965485175,
 0.35880747228772286,
 0.35799381539117314,
 0.35770847769137798,
 0.35759880157553514,
 0.35654010749545573,
 0.3558024350340232,
 0.35580222546439466,
 0.35559579476952274,
 0.35493999022449352,
 0.3538161165544072,
 0.35375558529017453,
 0.35348023985500171,
 0.35273104090213941,
 0.35260864855008667,
 0.35260413616085312,
 0.35250202234622197,
 0.35229228218902686,
 0.35217034565399519,
 0.35211870553195473,
 0.3516812681171016,
 0.35161122022747893,
 0.35151298318504298,
 0.35037178235617655,
 0.35034847282458353,
 0.35033210587037994,
 0.35030751286446665,
 0.3500937603607876,
 0.35000464463548003,
 0.34965123759858291,
 0.34900270741515127,
 0.34756175868151368,
 0.34680983150763856,
 0.3462854592098577,
 0.34620066720682763,
 0.34610027051936859,
 0.3459905351582051,
 0.34564247113901919,
 0.34552087456064023,
 0.34546601832290158,
 0.34517478904315574,
 0.34512345625568497,
 0.34473511422166919,
 0.34425667611144095,
 0.344182679979469,
 0.34359836082981121,
 0.34285939805900245,
 0.3428316847176141,
 0.34280864210825041,
 0.34213053093556334,
 0.34131880961047251,
 0.34124850592222927,
 0.34111592045629091,
 0.34105470858813958,
 0.34064382680215294,
 0.34030098122206909,
 0.3397873974058353,
 0.33909886921138244,
 0.33878491738805,
 0.33850837349473201,
 0.33796042408734139,
 0.3378492027460781,
 0.33704758103286753,
 0.33587028227650023,
 0.33553827254138513,
 0.33548799218678632,
 0.33532658815604988,
 0.33522580103389171,
 0.33438246172725472,
 0.33437243191957067,
 0.33409838214954263,
 0.33335402129541297,
 0.33318166911696834,
 0.33298155751803526,
 0.33285111386616861,
 0.33265456049859471,
 0.33229074002624481,
 0.33226265018546669,
 0.33207508569054311,
 0.33203424635640449,
 0.33191252237738222,
 0.33171601252031269,
 0.33167803137512242,
 0.33136385641174088,
 0.33108804877866427,
 0.33081459592596318,
 0.32924984218396136,
 0.32898008883350793,
 0.32897279032021054,
 0.32896398003114624,
 0.32821821159268699,
 0.32783030417457504,
 0.32780428608623097,
 0.32737072252446214,
 0.32701728724737777,
 0.32569674401556242,
 0.32544257398862753,
 0.32482530189628339,
 0.32459263810938571,
 0.32430362897044696,
 0.32429927840901107,
 0.32378103734498659,
 0.32358571627165506,
 0.32305241982391708,
 0.32250839917035157,
 0.32206717163625781,
 0.32200373676433769,
 0.32116537182281646,
 0.32062070256007547,
 0.32031194856294776,
 0.31993315169914305,
 0.31971328752929451,
 0.31944625154797401,
 0.31940280127397014,
 0.31874894038218343,
 0.31811333524359758,
 0.31793371259844666,
 0.31751448284773881,
 0.31736358551409505,
 0.31711006451631635,
 0.3168781997974281,
 0.31677262219035024,
 0.31637172233450334,
 0.31636217338011074,
 0.31455666149993294,
 0.31433315578433085,
 0.3135402875123588,
 0.3132096744992926,
 0.31296604178426146,
 0.31285020814479136,
 0.31282215389817536,
 0.31113230706838518,
 0.30960095456682329,
 0.30902760255481032,
 0.30894021537893751,
 0.30815667019688897,
 0.3078343945336578,
 0.30740975622150651,
 0.3073296521279667,
 0.30728138317802239,
 0.30706584016278671,
 0.30695975631804362,
 0.30679029171939842,
 0.30618329822700757,
 0.30589848880299297,
 0.30586576713570424,
 0.30580049326170372,
 0.30571351686916975,
 0.30536901736448757,
 0.30530201959528358,
 0.30483007615961205,
 0.30479026759865241,
 0.30388033962087474,
 0.30366166052220012,
 0.30346440867775348,
 0.30283334478604618,
 0.30279171601964372,
 0.30214859084478873,
 0.30203094659261015,
 0.30155910938853009,
 0.30123369378440301,
 0.30088329365487915,
 0.30017155835068521,
 0.30005073302460189,
 0.299801506214598,
 0.29950639996357181,
 0.29948367589207114,
 0.29898479655586457,
 0.29722262086138806,
 0.29691180140437717,
 0.29474269947529175,
 0.29472576333379152,
 0.29459162879264561,
 0.29373762673180159,
 0.29371082933157483,
 0.29320594298854502,
 0.29313153509027057,
 0.29290347602636418,
 0.29233157062170234,
 0.29198751454875654,
 0.29141470172945533,
 0.29076433160894199,
 0.29069628625388477,
 0.28976416199139399,
 0.28912227352499664,
 0.28905029683603878,
 0.28902586773705519,
 0.28863075948479039,
 0.28826813757792435,
 0.28817290243360871,
 0.28800956457382854,
 0.28787141122412424,
 0.28762689257602503,
 0.28562628846998628,
 0.28528503323073073,
 0.28465888130332745,
 0.28405728813720055,
 0.28323634210133253,
 0.28307585697943721,
 0.28280661547915192,
 0.28272791049299201,
 0.28243572100184644,
 0.28236658781605528,
 0.28209454249676363,
 0.2820088665562196,
 0.28180333212491115,
 0.2814594553690612,
 0.28144696711118389,
 0.28129124173946529,
 0.28107829211544233,
 0.28089734448410625,
 0.28061615366069248,
 0.27999422157316112,
 0.27996211734583198,
 0.27961159174747241,
 0.27868368088481021,
 0.27861167095544426,
 0.27859722881268661,
 0.27845693413376371,
 0.27791831362469538,
 0.27784869266719814,
 0.27761538785589801,
 0.27752188443300946,
 0.27723132627475994,
 0.27680912874590574,
 0.27671363166168345,
 0.27615392850721482,
 0.27549519673347495,
 0.27494132171209301,
 0.27480908861543685,
 0.27466511316224801,
 0.27398987619446535,
 0.2737084876009877,
 0.27329392347016146,
 0.27326271634383281,
 0.27288507986767263,
 0.27282087642110348,
 0.27229221756272309,
 0.27224650564604397,
 0.27203594658704933,
 0.27201972099779659,
 0.27201028747261302,
 0.27180603384107249,
 0.27115955679559334,
 0.27098007070750707,
 0.27066881396707021,
 0.26956739760101961,
 0.26919968648199943,
 0.26899790505316812,
 0.268950520287006,
 0.26813921438256544,
 0.26806533664881138,
 0.26726476181063874,
 0.26707411078409099,
 0.26695697076003594,
 0.26611237172717878,
 0.26605947644431471,
 0.26563462702372342,
 0.26550433369163734,
 0.26510022094337432,
 0.26485510281631913,
 0.26473007320586434,
 0.26433473634129961,
 0.26422652810724506,
 0.26402899255203877,
 0.26371279200294356,
 0.2634368972238908,
 0.26342266431063038,
 0.26318517377485134,
 0.26306742995797272,
 0.26304929924573384,
 0.26298902161048243,
 0.26283328317864396,
 0.26267938954531678,
 0.26265664836622593,
 0.26265460089192572,
 0.26262792321330763,
 0.26226670280462017,
 0.2620546251765743,
 0.26188202038275871,
 0.26175093390851417,
 0.26110203342082838,
 0.26109445153376343,
 0.26094391328676936,
 0.26073905813013465,
 0.26047549537094206,
 0.2589290196362749,
 0.25876739805634408,
 0.25868118415633523,
 0.25844262927252698,
 0.25835213305364363,
 0.25814619137401712,
 0.25799838363332106,
 0.25777842494870534,
 0.25767901524655834,
 0.25624879604375089,
 0.25595553284378925,
 0.25566651386724148,
 0.25565734605243151,
 0.25563974794646444,
 0.25507400489017035,
 0.25479822222145926,
 0.25466348489551288,
 0.25445984545646755,
 0.2543031097932163,
 0.25429027831118389,
 0.25413384221988206,
 0.25387773433716587,
 0.25330039068013721,
 0.25307995975427583,
 0.25288343154415016,
 0.25267816363497525,
 0.25251969045857564,
 0.25225076439009475,
 0.25221819687777824,
 0.25176077981961037,
 0.25175180926381358,
 0.25161977904950605,
 0.25150080739230574,
 0.25149221728583082,
 0.25143750908869372,
 0.25128030211848856,
 0.25124889625940122,
 0.25124131592664817,
 0.25079207915374357,
 0.24998054172803513,
 0.24998054172803513,
 0.24950440797335349,
 0.24942816222882913,
 0.24905594330438011,
 0.24898729381193629,
 0.24896348220909867,
 0.24875930620985962,
 0.24860447038233349,
 0.24851116594717382,
 0.24839889899793727,
 0.24825859911912182,
 0.24790251432509178,
 0.24784551564946819,
 0.24765653490341127,
 0.24763619851717233,
 0.24747225259455879,
 0.24729743806305535,
 0.24722726499512393,
 0.24712064055365468,
 0.24679057606314383,
 0.24676517048560376,
 0.24664707555988261,
 0.24604915123954363,
 0.24604915123954363,
 0.2458864193734342,
 0.24571818324160824,
 0.24565666924132057,
 0.24554174422181327,
 0.24514642783194024,
 0.24502672936904188,
 0.24487877698381647,
 0.24480406991866951,
 0.24461970048456844,
 0.24459312073526754,
 0.24455677461237704,
 0.24436274497077767,
 0.24427392455354199,
 0.24409405173424703,
 0.24403216693821903,
 0.24380725226027922,
 0.24370837211764715,
 0.24272964978206663,
 0.24264985219229221,
 0.24259832051323052,
 0.24245696124816854,
 0.24214571847590968,
 0.24193887100515282,
 0.24179141563583514,
 0.24130266054342991,
 0.24113864207509339,
 0.24069274112875197,
 0.24034329606436244,
 0.24021929586349147,
 0.24011047315540954,
 0.24009448511029713,
 0.23964511190418142,
 0.23963186660467006,
 0.23873933580801027,
 0.23855776529082853,
 0.23853301313795203,
 0.23843877295565941,
 0.2383485257694061,
 0.23828576177893529,
 0.23787690107229337,
 0.23767378981194062,
 0.23755838697743295,
 0.23748834943889488,
 0.23744385844749505,
 0.23728338219226169,
 0.23715674241356358,
 0.23712735478927285,
 0.23698749704733507,
 0.23656141060693606,
 0.23642976074093625,
 0.23636020245479752,
 0.23624753151641842,
 0.23621017337558634,
 0.23579141616824767,
 0.23558179936203191,
 0.23547065641714701,
 0.23524987661722546,
 0.23521581140701836,
 0.23508568657298437,
 0.23489024674856665,
 0.23474814643563416,
 0.23461519186827823,
 0.23451334985925756,
 0.23440146496763806,
 0.23440015926869509,
 0.23398108683954735,
 0.23375863018072784,
 0.233580256114643,
 0.23341584512947031,
 0.23332734826399787,
 0.23304013234939081,
 0.23285955490429378,
 0.2325686285425122,
 0.23238045464754339,
 0.23204100942621927,
 0.2319574846349835,
 0.2318778110337372,
 0.23172919335304193,
 0.23155774337961121,
 0.23140149230921728,
 0.23136310038613875,
 0.2310474963979039,
 0.23100866161232961,
 0.23026030188336674,
 0.23011068772275312,
 0.22984114958662913,
 0.22978179744050284,
 0.22972112565248751,
 0.2295580686054905,
 0.22924904384215289,
 0.22921860067041736,
 0.22882730057996492,
 0.22881059048869223,
 0.22852576417176085,
 0.22834275990643901,
 0.22806730584225343,
 0.22770513694293154,
 0.22767952887664369,
 0.2273761478157573,
 0.22713791991505303,
 0.22713246832729905,
 0.22712265534453557,
 0.22690714033696968,
 0.22689588182669423,
 0.22672088832667989,
 0.22585527421000928,
 0.22577471429966597,
 0.22567940467804448,
 0.22559691086681349,
 0.22548682825156771,
 0.2253856011219082,
 0.2251561233729602,
 0.22506959001255838,
 0.22497992942042055,
 0.22489502914683426,
 0.22483105013663568,
 0.22476283218806503,
 0.22452392094097617,
 0.22436850683311066,
 0.22418983961061514,
 0.22395969963443235,
 0.22365474995622925,
 0.22362841259120644,
 0.22361897470405862,
 0.22343915256576161,
 0.22323513695561792,
 0.22299311557912027,
 0.22254987429924969,
 0.22208815284614578,
 0.2218805658728725,
 0.22161893544137279,
 0.22159356721783405,
 0.22158265596842008,
 0.22124838566547697,
 0.22118288468157002,
 0.22110494360001032,
 0.22106489373473526,
 0.2208756368171817,
 0.22044678431361855,
 0.22041963807917905,
 0.22030326965843666,
 0.22027395860296672,
 0.22022318768690163,
 0.22021574900352525,
 0.22009154309249102,
 0.22004735173639572,
 0.2200293238379947,
 0.21996180224155534,
 0.21993298213425533,
 0.21980876643133787,
 0.21980400668208019,
 0.21962346185298398,
 0.21958797539648675,
 0.21918480082949945,
 0.21878460964839597,
 0.21868774725312701,
 0.21847188354894292,
 0.21846525025933902,
 0.21846525025933902,
 0.21836733933497665,
 0.21793337562601275,
 0.21784981024658442,
 0.21783820582768038,
 0.21774201162144144,
 0.21755433306865893,
 0.21747822812504902,
 0.21732449190504072,
 0.21716914437111573,
 0.21701150100082689,
 0.21650659896688826,
 0.21648353125676351,
 0.21627587722121727,
 0.2161610846308023,
 0.21614181005789268,
 0.21572111738966199,
 0.2156541773063457,
 0.2156541773063457,
 0.21558479511950809,
 0.21553460055993562,
 0.21512074249837709,
 0.21507432079766228,
 0.21500449809632757,
 0.21492547899381628,
 0.2148234980770666,
 0.21454252835196821,
 0.21420569629508301,
 0.21420569629508301,
 0.21413219318141696,
 0.21378790327864239,
 0.21325597390612991,
 0.21307936602800245,
 0.21297501475793776,
 0.21294765546401878,
 0.21285628612884366,
 0.21246139362319569,
 0.21243669375482538,

In [347]:
r1 = sorted(result[:,1], reverse = True)
roc_auc_score(y1_test,r1)

0.49692145920796332

In [ ]:
#r1

In [396]:
roc_auc_score(y1_test,result[:,1])

0.70315235055090908

In [61]:
#import lightgbm and xgboost 
import lightgbm as lgb 
import xgboost as xgb

ModuleNotFoundError: No module named 'lightgbm'